# Generated by Django 5.0.1 on 2024-01-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Metodo', models.CharField(max_length=200)),
                ('desc_metodo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado_cita', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('apellido', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=254)),
                ('clave', models.CharField(max_length=254)),
                ('foto', models.ImageField(default='fotos/default.png', upload_to='fotos/')),
                ('rol', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('SECRE', 'Secretaria'), ('VENDE', 'Vendedor'), ('USUAR', 'Usuario')], default='USUAR', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.IntegerField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.factura')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.metodo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ser', models.CharField(max_length=200)),
                ('desc_ser', models.TextField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(default='fotos_productos/default.png', upload_to='fotos_productos/')),
                ('id_categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reparado.solicitud'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=254)),
                ('estrellas', models.IntegerField()),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_historico', models.IntegerField()),
                ('foto', models.ImageField(default='fotos_productos/default.png', upload_to='fotos_productos/')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.servicio')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparado.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reparado.usuario'),
        ),
    ]
