# Generated by Django 5.0.1 on 2024-02-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0002_usuario_nick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clave',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nick',
            new_name='username',
        ),
    ]
