# Generated by Django 5.0.1 on 2024-02-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0003_rename_clave_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='stock',
        ),
    ]
