# Generated by Django 5.0.1 on 2024-02-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparado', '0004_remove_servicio_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='foto',
            field=models.ImageField(default='productos/default.png', upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='usuarios/default.png', upload_to='usuarios/'),
        ),
    ]
